name: CI

on:
#   pull_request:
#     branches: [ main ]

# env:
#   DEVELOPER_DIR: /Applications/Xcode_14.3.app

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v

  test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: swift test -v

